/* CVS $Id: $ */
package org.xenei.galway2020.vocab; 
import org.apache.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from file:/home/claude/git/galway2020/import/common/src/main/resources/vocabs/dcterms.rdf 
 * @author Auto-generated by schemagen on 20 Jul 2015 21:40 
 */
public class Dcterms {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://purl.org/dc/terms/";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>A summary of the resource.</p> */
    public static final Property abstract_ = m_model.createProperty( "http://purl.org/dc/terms/abstract" );
    
    /** <p>Information about who can access the resource or an indication of its security 
     *  status.</p>
     */
    public static final Property accessRights = m_model.createProperty( "http://purl.org/dc/terms/accessRights" );
    
    /** <p>The method by which items are added to a collection.</p> */
    public static final Property accrualMethod = m_model.createProperty( "http://purl.org/dc/terms/accrualMethod" );
    
    /** <p>The frequency with which items are added to a collection.</p> */
    public static final Property accrualPeriodicity = m_model.createProperty( "http://purl.org/dc/terms/accrualPeriodicity" );
    
    /** <p>The policy governing the addition of items to a collection.</p> */
    public static final Property accrualPolicy = m_model.createProperty( "http://purl.org/dc/terms/accrualPolicy" );
    
    /** <p>An alternative name for the resource.</p> */
    public static final Property alternative = m_model.createProperty( "http://purl.org/dc/terms/alternative" );
    
    /** <p>A class of entity for whom the resource is intended or useful.</p> */
    public static final Property audience = m_model.createProperty( "http://purl.org/dc/terms/audience" );
    
    /** <p>Date (often a range) that the resource became or will become available.</p> */
    public static final Property available = m_model.createProperty( "http://purl.org/dc/terms/available" );
    
    /** <p>A bibliographic reference for the resource.</p> */
    public static final Property bibliographicCitation = m_model.createProperty( "http://purl.org/dc/terms/bibliographicCitation" );
    
    /** <p>An established standard to which the described resource conforms.</p> */
    public static final Property conformsTo = m_model.createProperty( "http://purl.org/dc/terms/conformsTo" );
    
    /** <p>An entity responsible for making contributions to the resource.</p> */
    public static final Property contributor = m_model.createProperty( "http://purl.org/dc/terms/contributor" );
    
    /** <p>The spatial or temporal topic of the resource, the spatial applicability of 
     *  the resource, or the jurisdiction under which the resource is relevant.</p>
     */
    public static final Property coverage = m_model.createProperty( "http://purl.org/dc/terms/coverage" );
    
    /** <p>Date of creation of the resource.</p> */
    public static final Property created = m_model.createProperty( "http://purl.org/dc/terms/created" );
    
    /** <p>An entity primarily responsible for making the resource.</p> */
    public static final Property creator = m_model.createProperty( "http://purl.org/dc/terms/creator" );
    
    /** <p>A point or period of time associated with an event in the lifecycle of the 
     *  resource.</p>
     */
    public static final Property date = m_model.createProperty( "http://purl.org/dc/terms/date" );
    
    /** <p>Date of acceptance of the resource.</p> */
    public static final Property dateAccepted = m_model.createProperty( "http://purl.org/dc/terms/dateAccepted" );
    
    /** <p>Date of copyright.</p> */
    public static final Property dateCopyrighted = m_model.createProperty( "http://purl.org/dc/terms/dateCopyrighted" );
    
    /** <p>Date of submission of the resource.</p> */
    public static final Property dateSubmitted = m_model.createProperty( "http://purl.org/dc/terms/dateSubmitted" );
    
    /** <p>An account of the resource.</p> */
    public static final Property description = m_model.createProperty( "http://purl.org/dc/terms/description" );
    
    /** <p>A class of entity, defined in terms of progression through an educational 
     *  or training context, for which the described resource is intended.</p>
     */
    public static final Property educationLevel = m_model.createProperty( "http://purl.org/dc/terms/educationLevel" );
    
    /** <p>The size or duration of the resource.</p> */
    public static final Property extent = m_model.createProperty( "http://purl.org/dc/terms/extent" );
    
    /** <p>The file format, physical medium, or dimensions of the resource.</p> */
    public static final Property format = m_model.createProperty( "http://purl.org/dc/terms/format" );
    
    /** <p>A related resource that is substantially the same as the pre-existing described 
     *  resource, but in another format.</p>
     */
    public static final Property hasFormat = m_model.createProperty( "http://purl.org/dc/terms/hasFormat" );
    
    /** <p>A related resource that is included either physically or logically in the 
     *  described resource.</p>
     */
    public static final Property hasPart = m_model.createProperty( "http://purl.org/dc/terms/hasPart" );
    
    /** <p>A related resource that is a version, edition, or adaptation of the described 
     *  resource.</p>
     */
    public static final Property hasVersion = m_model.createProperty( "http://purl.org/dc/terms/hasVersion" );
    
    /** <p>An unambiguous reference to the resource within a given context.</p> */
    public static final Property identifier = m_model.createProperty( "http://purl.org/dc/terms/identifier" );
    
    /** <p>A process, used to engender knowledge, attitudes and skills, that the described 
     *  resource is designed to support.</p>
     */
    public static final Property instructionalMethod = m_model.createProperty( "http://purl.org/dc/terms/instructionalMethod" );
    
    /** <p>A related resource that is substantially the same as the described resource, 
     *  but in another format.</p>
     */
    public static final Property isFormatOf = m_model.createProperty( "http://purl.org/dc/terms/isFormatOf" );
    
    /** <p>A related resource in which the described resource is physically or logically 
     *  included.</p>
     */
    public static final Property isPartOf = m_model.createProperty( "http://purl.org/dc/terms/isPartOf" );
    
    /** <p>A related resource that references, cites, or otherwise points to the described 
     *  resource.</p>
     */
    public static final Property isReferencedBy = m_model.createProperty( "http://purl.org/dc/terms/isReferencedBy" );
    
    /** <p>A related resource that supplants, displaces, or supersedes the described 
     *  resource.</p>
     */
    public static final Property isReplacedBy = m_model.createProperty( "http://purl.org/dc/terms/isReplacedBy" );
    
    /** <p>A related resource that requires the described resource to support its function, 
     *  delivery, or coherence.</p>
     */
    public static final Property isRequiredBy = m_model.createProperty( "http://purl.org/dc/terms/isRequiredBy" );
    
    /** <p>A related resource of which the described resource is a version, edition, 
     *  or adaptation.</p>
     */
    public static final Property isVersionOf = m_model.createProperty( "http://purl.org/dc/terms/isVersionOf" );
    
    /** <p>Date of formal issuance (e.g., publication) of the resource.</p> */
    public static final Property issued = m_model.createProperty( "http://purl.org/dc/terms/issued" );
    
    /** <p>A language of the resource.</p> */
    public static final Property language = m_model.createProperty( "http://purl.org/dc/terms/language" );
    
    /** <p>A legal document giving official permission to do something with the resource.</p> */
    public static final Property license = m_model.createProperty( "http://purl.org/dc/terms/license" );
    
    /** <p>An entity that mediates access to the resource and for whom the resource is 
     *  intended or useful.</p>
     */
    public static final Property mediator = m_model.createProperty( "http://purl.org/dc/terms/mediator" );
    
    /** <p>The material or physical carrier of the resource.</p> */
    public static final Property medium = m_model.createProperty( "http://purl.org/dc/terms/medium" );
    
    /** <p>Date on which the resource was changed.</p> */
    public static final Property modified = m_model.createProperty( "http://purl.org/dc/terms/modified" );
    
    /** <p>A statement of any changes in ownership and custody of the resource since 
     *  its creation that are significant for its authenticity, integrity, and interpretation.</p>
     */
    public static final Property provenance = m_model.createProperty( "http://purl.org/dc/terms/provenance" );
    
    /** <p>An entity responsible for making the resource available.</p> */
    public static final Property publisher = m_model.createProperty( "http://purl.org/dc/terms/publisher" );
    
    /** <p>A related resource that is referenced, cited, or otherwise pointed to by the 
     *  described resource.</p>
     */
    public static final Property references = m_model.createProperty( "http://purl.org/dc/terms/references" );
    
    /** <p>A related resource.</p> */
    public static final Property relation = m_model.createProperty( "http://purl.org/dc/terms/relation" );
    
    /** <p>A related resource that is supplanted, displaced, or superseded by the described 
     *  resource.</p>
     */
    public static final Property replaces = m_model.createProperty( "http://purl.org/dc/terms/replaces" );
    
    /** <p>A related resource that is required by the described resource to support its 
     *  function, delivery, or coherence.</p>
     */
    public static final Property requires = m_model.createProperty( "http://purl.org/dc/terms/requires" );
    
    /** <p>Information about rights held in and over the resource.</p> */
    public static final Property rights = m_model.createProperty( "http://purl.org/dc/terms/rights" );
    
    /** <p>A person or organization owning or managing rights over the resource.</p> */
    public static final Property rightsHolder = m_model.createProperty( "http://purl.org/dc/terms/rightsHolder" );
    
    /** <p>A related resource from which the described resource is derived.</p> */
    public static final Property source = m_model.createProperty( "http://purl.org/dc/terms/source" );
    
    /** <p>Spatial characteristics of the resource.</p> */
    public static final Property spatial = m_model.createProperty( "http://purl.org/dc/terms/spatial" );
    
    /** <p>The topic of the resource.</p> */
    public static final Property subject = m_model.createProperty( "http://purl.org/dc/terms/subject" );
    
    /** <p>A list of subunits of the resource.</p> */
    public static final Property tableOfContents = m_model.createProperty( "http://purl.org/dc/terms/tableOfContents" );
    
    /** <p>Temporal characteristics of the resource.</p> */
    public static final Property temporal = m_model.createProperty( "http://purl.org/dc/terms/temporal" );
    
    /** <p>A name given to the resource.</p> */
    public static final Property title = m_model.createProperty( "http://purl.org/dc/terms/title" );
    
    /** <p>The nature or genre of the resource.</p> */
    public static final Property type = m_model.createProperty( "http://purl.org/dc/terms/type" );
    
    /** <p>Date (often a range) of validity of a resource.</p> */
    public static final Property valid = m_model.createProperty( "http://purl.org/dc/terms/valid" );
    
    /** <p>A resource that acts or has the power to act.</p> */
    public static final Resource Agent = m_model.createResource( "http://purl.org/dc/terms/Agent" );
    
    /** <p>The set of classes specified by the DCMI Type Vocabulary, used to categorize 
     *  the nature or genre of the resource.</p>
     */
    public static final Resource DCMIType = m_model.createResource( "http://purl.org/dc/terms/DCMIType" );
    
    /** <p>The set of conceptual resources specified by the Dewey Decimal Classification.</p> */
    public static final Resource DDC = m_model.createResource( "http://purl.org/dc/terms/DDC" );
    
    /** <p>The set of media types specified by the Internet Assigned Numbers Authority.</p> */
    public static final Resource IMT = m_model.createResource( "http://purl.org/dc/terms/IMT" );
    
    /** <p>The set of conceptual resources specified by the Library of Congress Classification.</p> */
    public static final Resource LCC = m_model.createResource( "http://purl.org/dc/terms/LCC" );
    
    /** <p>The set of labeled concepts specified by the Library of Congress Subject Headings.</p> */
    public static final Resource LCSH = m_model.createResource( "http://purl.org/dc/terms/LCSH" );
    
    /** <p>The set of labeled concepts specified by the Medical Subject Headings.</p> */
    public static final Resource MESH = m_model.createResource( "http://purl.org/dc/terms/MESH" );
    
    /** <p>The set of conceptual resources specified by the National Library of Medicine 
     *  Classification.</p>
     */
    public static final Resource NLM = m_model.createResource( "http://purl.org/dc/terms/NLM" );
    
    /** <p>The set of places specified by the Getty Thesaurus of Geographic Names.</p> */
    public static final Resource TGN = m_model.createResource( "http://purl.org/dc/terms/TGN" );
    
    /** <p>The set of conceptual resources specified by the Universal Decimal Classification.</p> */
    public static final Resource UDC = m_model.createResource( "http://purl.org/dc/terms/UDC" );
    
    /** <p>The set of regions in space defined by their geographic coordinates according 
     *  to the DCMI Box Encoding Scheme.</p>
     */
    public static final Resource Box = m_model.createResource( "http://purl.org/dc/terms/Box" );
    
    /** <p>The set of codes listed in ISO 3166-1 for the representation of names of countries.</p> */
    public static final Resource ISO3166 = m_model.createResource( "http://purl.org/dc/terms/ISO3166" );
    
    /** <p>The three-letter alphabetic codes listed in ISO639-2 for the representation 
     *  of names of languages.</p>
     */
    public static final Resource ISO639_2 = m_model.createResource( "http://purl.org/dc/terms/ISO639-2" );
    
    /** <p>The set of three-letter codes listed in ISO 639-3 for the representation of 
     *  names of languages.</p>
     */
    public static final Resource ISO639_3 = m_model.createResource( "http://purl.org/dc/terms/ISO639-3" );
    
    /** <p>The set of time intervals defined by their limits according to the DCMI Period 
     *  Encoding Scheme.</p>
     */
    public static final Resource Period = m_model.createResource( "http://purl.org/dc/terms/Period" );
    
    /** <p>The set of points in space defined by their geographic coordinates according 
     *  to the DCMI Point Encoding Scheme.</p>
     */
    public static final Resource Point = m_model.createResource( "http://purl.org/dc/terms/Point" );
    
    /** <p>The set of tags, constructed according to RFC 1766, for the identification 
     *  of languages.</p>
     */
    public static final Resource RFC1766 = m_model.createResource( "http://purl.org/dc/terms/RFC1766" );
    
    /** <p>The set of tags constructed according to RFC 3066 for the identification of 
     *  languages.</p>
     */
    public static final Resource RFC3066 = m_model.createResource( "http://purl.org/dc/terms/RFC3066" );
    
    /** <p>The set of tags constructed according to RFC 4646 for the identification of 
     *  languages.</p>
     */
    public static final Resource RFC4646 = m_model.createResource( "http://purl.org/dc/terms/RFC4646" );
    
    /** <p>The set of tags constructed according to RFC 5646 for the identification of 
     *  languages.</p>
     */
    public static final Resource RFC5646 = m_model.createResource( "http://purl.org/dc/terms/RFC5646" );
    
    /** <p>The set of identifiers constructed according to the generic syntax for Uniform 
     *  Resource Identifiers as specified by the Internet Engineering Task Force.</p>
     */
    public static final Resource URI = m_model.createResource( "http://purl.org/dc/terms/URI" );
    
    /** <p>The set of dates and times constructed according to the W3C Date and Time 
     *  Formats Specification.</p>
     */
    public static final Resource W3CDTF = m_model.createResource( "http://purl.org/dc/terms/W3CDTF" );
    
}
