/* CVS $Id: $ */
package org.xenei.galway2020.vocab; 
import org.apache.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from file:/home/claude/git/galway2020/import/common/src/main/resources/vocabs/rdf-schema.ttl 
 * @author Auto-generated by schemagen on 13 Jul 2015 18:21 
 */
public class Rdf_schema {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.w3.org/2000/01/rdf-schema#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>A description of the subject resource.</p> */
    public static final Property comment = m_model.createProperty( "http://www.w3.org/2000/01/rdf-schema#comment" );
    
    /** <p>A domain of the subject property.</p> */
    public static final Property domain = m_model.createProperty( "http://www.w3.org/2000/01/rdf-schema#domain" );
    
    /** <p>The defininition of the subject resource.</p> */
    public static final Property isDefinedBy = m_model.createProperty( "http://www.w3.org/2000/01/rdf-schema#isDefinedBy" );
    
    /** <p>A human-readable name for the subject.</p> */
    public static final Property label = m_model.createProperty( "http://www.w3.org/2000/01/rdf-schema#label" );
    
    /** <p>A member of the subject resource.</p> */
    public static final Property member = m_model.createProperty( "http://www.w3.org/2000/01/rdf-schema#member" );
    
    /** <p>A range of the subject property.</p> */
    public static final Property range = m_model.createProperty( "http://www.w3.org/2000/01/rdf-schema#range" );
    
    /** <p>Further information about the subject resource.</p> */
    public static final Property seeAlso = m_model.createProperty( "http://www.w3.org/2000/01/rdf-schema#seeAlso" );
    
    /** <p>The subject is a subclass of a class.</p> */
    public static final Property subClassOf = m_model.createProperty( "http://www.w3.org/2000/01/rdf-schema#subClassOf" );
    
    /** <p>The subject is a subproperty of a property.</p> */
    public static final Property subPropertyOf = m_model.createProperty( "http://www.w3.org/2000/01/rdf-schema#subPropertyOf" );
    
}
